# Generated by Django 6.0 on 2026-01-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=8),
            preserve_default=False,
        ),
    ]
