# Generated by Django 6.0 on 2026-01-15 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
